return {
  "github/copilot.vim",
  -- "zbirenbaum/copilot.lua",
  -- cmd = "Copilot",
  -- event = "InsertEnter",
  -- config = function()
  -- 	require("copilot").setup({
  -- 		panel = {
  -- 			enabled = false,
  -- 			auto_refresh = false,
  -- 			keymap = {
  -- 				jump_prev = "[[",
  -- 				jump_next = "]]",
  -- 				accept = "<CR>",
  -- 				refresh = "gr",
  -- 				open = "<M-CR>",
  -- 			},
  -- 			layout = {
  -- 				position = "bottom", -- | top | left | right
  -- 				ratio = 0.4,
  -- 			},
  -- 		},
  -- 		suggestion = {
  -- 			enabled = true,
  -- 			auto_trigger = true,
  -- 			debounce = 75,
  -- 			keymap = {
  -- 				accept = "<M-y>",
  -- 				accept_word = false,
  -- 				accept_line = false,
  -- 				next = "<M-]>",
  -- 				prev = "<M-[>",
  -- 				dismiss = "<C-]>",
  -- 			},
  -- 		},
  -- 		filetypes = {
  -- 			help = false,
  -- 			gitcommit = false,
  -- 			gitrebase = false,
  -- 			hgcommit = false,
  -- 			svn = false,
  -- 			cvs = false,
  -- 			["."] = false,
  -- 		},
  -- 		copilot_node_command = "/home/sulthonuladib/.nvm/versions/node/v20.15.1/bin/node", -- Node.js version must be > 18.x
  -- 		server_opts_overrides = {},
  -- 	})
  -- end,
}
